server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: "/h2"
      enabled: true

application:
  authServer:
    path: http://localhost:8083
    endpoint:
      auth: /auth/realms/master/protocol/openid-connect/token
      registerUser: /auth/admin/realms/esuarez/users
    user: admin
    password: pass