server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:6603/roomies
    username: root
    password: ***
  h2:
    console:
      path: "/h2"
      enabled: true

application:
  authServer:
    path: http://localhost:8083
    endpoint:
      auth: /auth/realms/master/protocol/openid-connect/token
      registerUser: /auth/admin/realms/esuarez/users
    user: admin
    password: pass